name: CD to On Premise Server

on:
  push:
    branches:
      - "on-premise-release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CR_PAT: ${{ secrets.CR_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            src:
              - 'src/**'
              - 'Dockerfile'
              - 'nginx.conf'
              - 'package*.json'
            conf:
              - 'docker-compose.yml'

      - name: Build image and Publish
        if: steps.changes.outputs.src == 'true'
        run: |
          echo $CR_PAT | docker login ghcr.io --username ${{secrets.GHCR_USER}} --password-stdin
          docker build --tag ghcr.io/${{secrets.GHCR_USER}}/bio-beacon-app:latest .
          docker push ghcr.io/${{secrets.GHCR_USER}}/bio-beacon-app:latest

      - name: Copy configuration files
        if: steps.changes.outputs.conf == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: "docker-compose.yml"
          target: ${{ secrets.SERVER_TARGET_LOCATION }}

      - name: Pull and Redeploy the Application
        if: steps.changes.outputs.src == 'true' || steps.changes.outputs.conf == 'true'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ${{ secrets.SERVER_TARGET_LOCATION}}
            docker pull ghcr.io/${{secrets.GHCR_USER}}/bio-beacon-app:latest
            docker compose up -d --build
            docker image prune -f
